---
all:
    hosts:
        itpfansibledev.web.illinois.edu:
            ansible_user: itpfansibledev
        itpfansibletest.web.illinois.edu:
            ansible_user: itpfansibletest
        itpfansibleprod.web.illinois.edu:
            ansible_user: itpfansibleprod
    vars:
        ansible_host: web.illinois.edu
