---
myapp_db_name: "{{ ansible_user }}_myapp"
myapp_dbuser_name: "{{ ansible_user }}_myapp"
myapp_dbprivs:
    - ALTER
    - ALTER ROUTINE
    - CREATE
    - CREATE ROUTINE
    - CREATE VIEW
    - DELETE
    - DROP
    - EXECUTE
    - INDEX
    - INSERT
    - REFERENCES
    - SELECT
    - SHOW VIEW
    - TRIGGER
    - UPDATE
myapp_phpver: ea-php70
